services:
  powertool:
    build: .
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 172.10.10.24

  server:
    image: alpine:latest
    expose:
      - "22"
    networks:
      backend:
        ipv4_address: 172.10.10.25
    command: >
      sh -c "apk add --no-cache openssh 
      && ssh-keygen -A 
      && echo 'root:pqu3ihrfai8dfz3?1sd' | chpasswd 
      && sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config 
      && /usr/sbin/sshd -D -e"

  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    networks:
      - backend
    cap_add:
      - SYS_ADMIN  # Allows bubblewrap to create namespaces (for mail)
    security_opt:
      - seccomp:unconfined # Disables the syscall filter that blocks sandboxing (for mail)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - TITLE=ClientTop
      - CUSTOM_USER=hans.habicht
      - PASSWORD=Remington
      - LC_ALL=de_DE.UTF-8
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=evolution|eog|libfuse2|iputils-ping|vim|nmap
    ports:
      - "3000:3000"
    shm_size: "1gb"
    volumes:
      - ./desktop:/config/Desktop/
      # - ./init/copy-bookmarks.sh:/custom-cont-init.d/copy-bookmarks.sh:ro
      # - ./init/set-wallpaper.sh:/custom-cont-init.d/set-wallpaper.sh:ro
      - ./init/setup-shortcuts.sh:/custom-cont-init.d/setup-shortcuts.sh:ro

networks:
  backend:
    ipam:
      config:
        - subnet: 172.10.10.0/24