services:
  powertool:
    build: .
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 172.10.10.24

  server:
    image: alpine:latest
    expose:
      - "22"
    networks:
      backend:
        ipv4_address: 172.10.10.25
    volumes:
      - ./BACKUP_2026_06_02.csv:/root/BACKUPS/BACKUP_2026_06_02.csv
    command: >
      sh -c "apk add --no-cache openssh 
      && ssh-keygen -A 
      && echo 'root:pqu3ihrfai8dfz3?1sd' | chpasswd 
      && sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config 
      && /usr/sbin/sshd -D -e"

  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    networks:
      - backend
#    cap_add:
#      - SYS_ADMIN  # Allows bubblewrap to create namespaces (for mail)
#    security_opt:
#      - seccomp:unconfined # Disables the syscall filter that blocks sandboxing (for mail)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - TITLE=ClientTop
      - CUSTOM_USER=hans.habicht
      - PASSWORD=Remington
      - LC_ALL=de_DE.UTF-8
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=iproute2|jq|libfuse2|iputils-ping|vim|nmap
    ports:
      - "3000:3000"
      - "3001:3001" ## https mit selfsigned Cert
    shm_size: "1gb"
    volumes:
      - ./config:/config #on initialization directory gets filled
      - ./desktop:/webtop_configurations:ro
      - ./init/1-copy-files.sh:/custom-cont-init.d/1-copy-files.sh:ro
      - ./init/2-set-autostart.sh:/custom-cont-init.d/2-set-autostart.sh:ro
      - ./init/3-copy-bookmarks.sh:/custom-cont-init.d/3-copy-bookmarks.sh:ro
      - ./init/4-setup-shortcuts.sh:/custom-cont-init.d/4-setup-shortcuts.sh:ro

networks:
  backend:
    ipam:
      config:
        - subnet: 172.10.10.0/24
